apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmt-producer
spec:
  selector:
    matchLabels:
      app: pmt-producer
  template:
    metadata:
      labels:
        app: pmt-producer
    spec:
      containers:
      - name: pmt-producer
        image: pmt-producer
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
        ports:
        - containerPort: 8080
        env:
          - name: KAFKA_URL
            value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local
          - name: CLUSTER
            value: c1
          - name: TOPIC
            value: credit-transfer-transactions
          - name: POD
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace