version: "3.8"
services:
  broker:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=broker
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
  pmt-producer:
    #https://stackoverflow.com/questions/60862687/how-to-create-docker-compose-yml-file-while-using-jib
    image: pmt-producer:latest
    links:
      - broker
      - jaeger
    environment:
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://jaeger:4318/v1/traces
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
  hz:
    image: hazelcast/hazelcast:5.3.6
    ports:
      - "5701:5701"
    environment:
      HZ_CLUSTERNAME: dev
  hz-mc:
    image: hazelcast/management-center:latest-snapshot
    ports:
      - "8080:8080"