---
# vars file for k8s/roles/gke
zone: asia-south1-a
region: asia-south1
location: asia
project_id: solution-architects-415712
docker_credentials_file: "{{ lookup('env','HOME') }}/.docker/config.json"
repository_id: "rajbarua-docker"

