
######################
## pipeline via CLC for data generator
######################
- name: Execute maven pom file to build the jar
  shell: mvn clean install -f pom.xml -DskipTests=true
  args:
    chdir: ../
  tags:
    - gen-job
- name: Find out the External IP of hz-primary-0
  shell: "kubectl get service hz-primary-0 -n default -o jsonpath='{.status.loadBalancer.ingress[0].ip}'"
  register: hz_primary_ip
  until: hz_primary_ip.stdout != ""
  retries: 10
  delay: 10
  tags:
    - gen-job
- name: Add the external IP to CLC config
  # shell: "clc config add hz-primary cluster.address={{hz_primary_ip.stdout}}:5701 cluster.name=hz-primary ssl.enabled=true ssl.skip-verify=true"
  shell: "clc config add hz-primary cluster.address={{hz_primary_ip.stdout}}:5701 cluster.name=hz-primary"
  tags:
    - gen-job
- name: Execute Hazelcast Command Line Client to deploy the code
  shell: clc -c hz-primary job submit ../generator/target/generator-1.0.0-SNAPSHOT.jar --class com.hz.demo.gen.job.GenOracle
  tags:
    - gen-job

