---
# vars file for k8s/roles/gke
zone: asia-south1-a
region: asia-south1
location: asia
project_id: solution-architects-415712
gcloud_sa_path: "gcp/credentials.json"
credentials_file: "{{ lookup('env','HOME') }}/{{ gcloud_sa_path }}"
repository_id: "rajbarua-docker"
self_signed_cert_key_file: "~/hazelcast/hazelcast.key"
self_signed_cert_cert_file: "~/hazelcast/hazelcast.pem"
self_signed_cert_keystore_file: "~/hazelcast/hazelcast-keystore.jks"


